### ISSUE TITLE
Add support for auto plugins

### ISSUE THREAD

**Issue by JosephEarl** [etsy/sbt-checkstyle-plugin#16]
See http://www.scala-sbt.org/0.13/docs/Plugins.html for more info

Since this would be a breaking change, maybe we should also do some or all of the following:

* Remove the deprecated configFile setting
* Remove "checkstyle" from the start of each setting
* Make sure parameter names match Maven plugin
* Move XSLTSettings into Checkstyle or move everything to com.etsy.sbt.checkstyle to make importing better

**Comment by ajsquared** [comment]
Good call.  Converting this to an auto plugin has been on the backlog for a while.

I'm on board with making all of the the other changes as well.

**Comment by ajsquared** [comment]
I've just published version 2.0.0 in which this has been converted to an AutoPlugin.  It should be available in Maven Central in the next few hours at the latest.
