### ISSUE TITLE
Path configurable

### ISSUE THREAD

**Issue by jmgreenberg** [etsy/sbt-checkstyle-plugin#23]
I have a mulit project. One of those projects consists mainly of generated code and I don't want to run checkstyle on those files.  Is there  a way to specific a subdirectory to run checkstyle on instead of the entire project?

**Comment by ajsquared** [comment]
If your generated source files end up in one of the directories in `managedSourceDirectories` they wouldn't get included, but if they're in the standard `javaSource` directory they would.  Currently there's not support for filtering the source files processed for a particular project.

You could also run checkstyle just on particular projects like `project1/checkstyle`.  Do either of those options help you?

**Comment by jmgreenberg** [comment]
I didn't know you could do `project1/checkstyle`. That works. Thanks!
