### ISSUE TITLE
New Feature: support for generating a XLST formatted report

### ISSUE THREAD

**Issue by andrewdbate** [etsy/sbt-checkstyle-plugin#3]
At the moment, the plugin does not support formatting of the XML report by using an XLST style sheet. Would it be possible to add this feature? (Reading the XML itself isn't as easy as reading a formatted version.) I believe that checkstyle itself includes style files that could be used.

**Comment by ajsquared** [comment]
That is a good idea, I'll take a look at the style sheets checkstyle provides.

**Comment by andrewdbate** [comment]
I've spent some time Googling, and, although I'm reasonably new to checkstyle, it appears that the use of `xsl` style files is not very well documented. I tried the style file available [here](https://java.net/projects/cougarsquared/sources/svn/content/trunk/buildsystem/checkstyle/contrib/checkstyle-noframes.xsl?rev=2236 here), and it seemed to produce good output.

I haven't worked out how to use style files with the tool yet; I just edited the `xml` file after it was generated to add the line `<?xml-stylesheet type="text/xsl" href="checkstyle-noframes.xsl" ?>` immediately after the line `<?xml version="1.0" encoding="UTF-8"?>`.

**Comment by ajsquared** [comment]
Interesting, I'm not that familiar with using the style files with it either.

**Comment by andrewdbate** [comment]
I should also add that the use of style files seems to be fairly easy when checkstyle is used with Ant; see [here](http://checkstyle.sourceforge.net/anttask.html). I think this is because Ant supports XSLT transformations directly (see [here](https://ant.apache.org/manual/Tasks/style.html)).

The code extract from the first link shows that the style can be specified with `<style in="checkstyle_report.xml" out="checkstyle_report.html" style="checkstyle.xsl"/>`. (However, Ant's documentation suggests that the `style` task is the deprecated name for the `xslt` task.)

I don't know whether an XSLT transformation is the only way to do it though.

**Comment by ajsquared** [comment]
Okay, that is helpful to dig into this more.  I suspect a similar plugin for SBT already exists or would be easy to add.
