### ISSUE TITLE
Update Checkstyle to 6.13

### ISSUE THREAD

**Issue by JosephEarl** [etsy/sbt-checkstyle-plugin#7]
Latest Checkstyle versions include some improvements, including support for Lambdas.

**Comment by ajsquared** [comment]
I'll take a look, but assuming they haven't made any major changes to checkstyle since 6.5 I should be able to update it this week.

**Comment by JosephEarl** [comment]
Was going to submit a PR for this myself if it wasn't too difficult. 

Also I wonder about making the version configurable at runtime like they do in the Maven plugin https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html. This would save having to update the SBT plugin for each minor Checkstyle release.

**Comment by ajsquared** [comment]
By all means send a PR if you'd like!  We're happy to accept contributions :)

I think you could do something similar in your build definition to change the checkstyle version without updating the plugin by setting `libraryDependencies` in the plugins.sbt file.  It would be good though to either have more explicit support for overriding the version or a documented example.

**Comment by JosephEarl** [comment]
Will give it a try!

**Comment by JosephEarl** [comment]
And the option to override to the dependency is to add the following to your plugins.sbt:

    dependencyOverrides += "com.puppycrawl.tools" % "checkstyle" % "6.13"

e.g.

    addSbtPlugin("com.etsy" % "sbt-checkstyle-plugin" % "0.5.1")
    dependencyOverrides += "com.puppycrawl.tools" % "checkstyle" % "6.13"

**Comment by ajsquared** [comment]
I merged your PR.  I'll publish a new version with your changes included soon.
